version: '3.9'

networks:
  dev:
    driver: bridge

services:
  docker-project: 
    build: 
      context: .
      dockerfile: Dockerfile
    image: dockerproject
    depends_on:
      - "app_db"
    container_name: dockerproject-services
    ports:
      - "8088:80"
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=app_db;Port=5432;Database=DockerProjectDbDriver;Pooling=true;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - dev

  app_db:
    image: postgres:latest
    container_name: app_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: DockerProjectDbDriver
    restart: always
    networks:
      - dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs
    ports:
      - "3000:3000"
    networks:
      - dev
    depends_on:
      - docker-project